import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Produto from '#models/produto'
export default class extends BaseSeeder {
  async run() {
    await Produto.createMany([
      {
        nome: 'Foster',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 100,
        preco_pix: 82.9,
        preco_cartao: 85.0,
      },
      {
        nome: 'Chacal',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 80,
        preco_pix: 71.9,
        preco_cartao: 75.0,
      },
      {
        nome: 'Tuko',
        animal: 'Cachorro',
        peso_saco: 14,
        quantidade: 120,
        preco_pix: 64.9,
        preco_cartao: 69.9,
      },
      {
        nome: 'Multidog',
        tipo: 'Vitaminada',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 90,
        preco_pix: 98.9,
        preco_cartao: 102.0,
      },
      {
        nome: 'Multidog',
        tipo: 'Chips',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 90,
        preco_pix: 98.9,
        preco_cartao: 102.0,
      },
      {
        nome: 'Multidog',
        tipo: 'Especial - Batata Doce',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 90,
        preco_pix: 98.9,
        preco_cartao: 102.0,
      },
      {
        nome: 'Golden',
        tipo: 'Adulto',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 60,
        preco_pix: 168.0,
        preco_cartao: 170.0,
      },
      {
        nome: 'Golden',
        tipo: 'Mini Bits',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 50,
        preco_pix: 168.0,
        preco_cartao: 170.0,
      },
      {
        nome: 'Golden',
        tipo: 'Filhote',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 50,
        preco_pix: 138.0,
        preco_cartao: 140.0,
      },
      {
        nome: 'Golden',
        tipo: 'Carne',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 50,
        preco_pix: 158.0,
        preco_cartao: 162.0,
      },
      {
        nome: 'Finotrato',
        tipo: 'Gold',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 178.0,
        preco_cartao: 180.0,
      },
      {
        nome: 'Finotrato',
        tipo: 'Filhote',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 202.0,
        preco_cartao: 205.0,
      },
      {
        nome: 'Finotrato ',
        tipo: 'Active',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 162.0,
        preco_cartao: 162.0,
      },
      {
        nome: 'Finotrato ',
        tipo: 'Senior',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 162.0,
        preco_cartao: 162.0,
      },
      {
        nome: 'Bonavita',
        tipo: 'Filhote',
        animal: 'Cachorro',
        peso_saco: 10,
        quantidade: 40,
        preco_pix: 138.0,
        preco_cartao: 140.0,
      },
      {
        nome: 'Bonavita',
        tipo: 'Adulto',
        animal: 'Cachorro',
        peso_saco: 10,
        quantidade: 40,
        preco_pix: 150.0,
        preco_cartao: 150.0,
      },
      {
        nome: 'Whiskas',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 110,
        preco_pix: 170.0,
        preco_cartao: 170.0,
      },
      {
        nome: 'Multicat',
        tipo: 'Mix',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 130,
        preco_pix: 89.9,
        preco_cartao: 92.0,
      },
      {
        nome: 'Multicat',
        tipo: 'Castrado',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 95,
        preco_pix: 119.0,
        preco_cartao: 123.0,
      },
      {
        nome: 'Golden',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 95,
        preco_pix: 160.0,
        preco_cartao: 162.0,
      },
      {
        nome: 'Golden',
        tipo: 'Castrado',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 95,
        preco_pix: 176.0,
        preco_cartao: 178.0,
      },
      {
        nome: 'Crescimento',
        animal: 'Galinha',
        peso_saco: 20,
        quantidade: 150,
        preco_pix: 81.0,
        preco_cartao: 81.0,
      },
      {
        nome: 'Milho',
        tipo: 'Grão',
        animal: 'Galinha',
        peso_saco: 15,
        quantidade: 160,
        preco_pix: 44.0,
        preco_cartao: 44.0,
      },
      {
        nome: 'Milho',
        tipo: 'Picado',
        animal: 'Galinha',
        peso_saco: 15,
        quantidade: 160,
        preco_pix: 47.0,
        preco_cartao: 47.0,
      },
      {
        nome: 'Coelho',
        animal: 'Coelho',
        peso_saco: 20,
        quantidade: 80,
        preco_pix: 86.0,
        preco_cartao: 86.0,
      },
    ])
  }
}
