import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Produto from '#models/produto'
export default class extends BaseSeeder {
  async run() {
    await Produto.createMany([
      {
        nome: 'Foster',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 100,
        preco_pix: 82.9,
        preco_cartao: 85.0,
        imagem: 'xcn3ahp3lqrfryetvkwaz4bx.webp',
      },
      {
        nome: 'Chacal',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 80,
        preco_pix: 71.9,
        preco_cartao: 75.0,
        imagem: 't1y6r9pq9wj97dhfhj538p86.webp',
      },
      {
        nome: 'Tuko',
        animal: 'Cachorro',
        peso_saco: 14,
        quantidade: 120,
        preco_pix: 64.9,
        preco_cartao: 69.9,
        imagem: 'ych7mf6611ot8rkgdop3n20g.webp',
      },
      {
        nome: 'Multidog',
        tipo: 'Vitaminada',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 90,
        preco_pix: 98.9,
        preco_cartao: 102.0,
        imagem: 'sftp6ukkf8g92ecjtwgfvgvy.webp',
      },
      {
        nome: 'Multidog',
        tipo: 'Chips',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 90,
        preco_pix: 98.9,
        preco_cartao: 102.0,
        imagem: 'k9kc031c3zl1cjjq56l80mcd.webp',
      },
      {
        nome: 'Multidog',
        tipo: 'Especial - Batata Doce',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 90,
        preco_pix: 98.9,
        preco_cartao: 102.0,
        imagem: 'uix6p2gmvnm62kbr69t42vqv.webp',
      },
      {
        nome: 'Golden',
        tipo: 'Adulto',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 60,
        preco_pix: 168.0,
        preco_cartao: 170.0,
        imagem: 'l44wdylgpdsc3sy1giw7r1qr.webp',
      },
      {
        nome: 'Golden',
        tipo: 'Mini Bits',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 50,
        preco_pix: 168.0,
        preco_cartao: 170.0,
      },
      {
        nome: 'Golden',
        tipo: 'Filhote',
        animal: 'Cachorro',
        peso_saco: 10,
        quantidade: 50,
        preco_pix: 138.0,
        preco_cartao: 140.0,
        imagem: 'yfwx79oje5ds1kicy5jro9lz.webp',
      },
      {
        nome: 'Golden',
        tipo: 'Carne',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 50,
        preco_pix: 158.0,
        preco_cartao: 162.0,
        imagem: 'qh0zr4ojudkqa2r4spy2zocz.webp',
      },
      {
        nome: 'Finotrato',
        tipo: 'Gold',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 178.0,
        preco_cartao: 180.0,
        imagem: 'vzk5nci73c08e0to79yiyewy.webp',
      },
      {
        nome: 'Finotrato',
        tipo: 'Filhote',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 202.0,
        preco_cartao: 205.0,
        imagem: 'elrqftog4ja0762eb4iy1h5o.webp',
      },
      {
        nome: 'Finotrato ',
        tipo: 'Active',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 162.0,
        preco_cartao: 162.0,
        imagem: 'n3wci5bxhjtdqifwwf16adw6.webp',
      },
      {
        nome: 'Finotrato ',
        tipo: 'Senior',
        animal: 'Cachorro',
        peso_saco: 15,
        quantidade: 70,
        preco_pix: 162.0,
        preco_cartao: 162.0,
      },
      {
        nome: 'Bonavita',
        tipo: 'Filhote',
        animal: 'Cachorro',
        peso_saco: 10,
        quantidade: 40,
        preco_pix: 138.0,
        preco_cartao: 140.0,
      },
      {
        nome: 'Bonavita',
        tipo: 'Adulto',
        animal: 'Cachorro',
        peso_saco: 10,
        quantidade: 40,
        preco_pix: 150.0,
        preco_cartao: 150.0,
      },
      {
        nome: 'Whiskas',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 110,
        preco_pix: 170.0,
        preco_cartao: 170.0,
        imagem: 'qcf0w5x0jfp4asijqonckjcy.webp',
      },
      {
        nome: 'Multicat',
        tipo: 'Mix',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 130,
        preco_pix: 89.9,
        preco_cartao: 92.0,
        imagem: 'a1t2ev0lq2tsmnbifchnlm9j.webp',
      },
      {
        nome: 'Multicat',
        tipo: 'Castrado',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 95,
        preco_pix: 119.0,
        preco_cartao: 123.0,
        imagem: 'dx59ye1aktqcvh53uhk7nba9.webp',
      },
      {
        nome: 'Golden',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 95,
        preco_pix: 160.0,
        preco_cartao: 162.0,
        imagem: 'f4fdaglg27glfq6z81jujwgc.webp',
      },
      {
        nome: 'Golden',
        tipo: 'Castrado',
        animal: 'Gato',
        peso_saco: 10,
        quantidade: 95,
        preco_pix: 176.0,
        preco_cartao: 178.0,
        imagem: 'bs8lysn2hrbqdt8fonkzarhw.webp',
      },
      {
        nome: 'Crescimento',
        animal: 'Galinha',
        peso_saco: 20,
        quantidade: 150,
        preco_pix: 81.0,
        preco_cartao: 81.0,
        imagem: 'elfaxbn6lvakq0y0lef1baun.webp',
      },
      {
        nome: 'Milho',
        tipo: 'Grão',
        animal: 'Galinha',
        peso_saco: 15,
        quantidade: 160,
        preco_pix: 44.0,
        preco_cartao: 44.0,
        imagem: 'auuxoilaprhlmuaxhwbqupuf.webp',
      },
      {
        nome: 'Milho',
        tipo: 'Picado',
        animal: 'Galinha',
        peso_saco: 15,
        quantidade: 160,
        preco_pix: 47.0,
        preco_cartao: 47.0,
        imagem: 'auuxoilaprhlmuaxhwbqupuf.webp',
      },
      {
        nome: 'Coelho',
        animal: 'Coelho',
        peso_saco: 20,
        quantidade: 80,
        preco_pix: 86.0,
        preco_cartao: 86.0,
        imagem: 'ladzi8wkilikt3hycon1dng5.webp',
      },
    ])
  }
}
